### PR TITLE
Milestone 2.friendships v1

### PR DESCRIPTION
**Pull request by smy5152**

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
- Good work creating a foundation to work on.

## However, there are some changes required 👀 🧰 🔨 🔧
- There really aren't any buttons on your project to add friends or accept/reject friendships. Please add them.
- I can see all posts by all users. I should only be able to see my own posts and those of my friends. Please filter out the posts show page to achieve this.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, there @smy5152 👋🏾 👋🏾 you are making great progress on this milestone 😄 You have worked on the feedback given by the previous TSE. However before approval, please fix the following ⬇️ 

- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User has to accept friendship request to start a friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x]  User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Add Unit and Integration tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

**HINT** You can read this Article on [Implementing friendships in active record](https://smartfunnycool.com/friendships-in-activerecord/)

That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

**Comment by smy5152** [comment]
@mimipeshy Please can we do a quick zoom call? The above points are covered.  I am adding screenshots to the docs and Readme now.

Specs I am writing right now.

**Comment by mimipeshy** [comment]
> @mimipeshy Please can we do a quick zoom call? The above points are covered. I am adding screenshots to the docs and Readme now.
> 
> Specs I am writing right now.

@smy5152 Good job on working on those changes 😄 , kindly request another code review from your student dashboard

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: 
--------
HELLO, @smy5152 Great job working on the required changes :muscle: :1st_place_medal: 
There is only one thing to make to complete this milestone. :hammer_and_wrench:  see it below :eyes: :point_down: 
--------------
- [x] Please add unit test.  you write on the pull request that you were working on them but there is no test at all. 
-----------
Please add the above and send it again for another review :+1: 
HAPPY CODING!!!

**Comment by smy5152** [comment]
@BrianSammit Thank you for the review. I was about to commit 🔢 
Sorry about that.

Yes, I was confused when the previous review highlighted the features not present. I will push the rspecs now.
Thanks.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 
Hello @smy5152 👋🏾 👋🏾 great job on adding the unit tests, they are passing. Therefore I will go ahead and mark this milestone as complete, go ahead and merge. All the best in the next milestone 😄 

Regards
Peris Ndanu

**Pull request merged**
